# -*- coding: utf-8 -*-
"""RareDiseaseProject#2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWp5-kQgY9hfhIFrq0Kfy6lo7M0L1ViZ
"""

from google.colab import drive
drive.mount('/content/drive')

import os
base_path = '/content/drive/My Drive/dataset/RareDiseaseAnalysis'
asmd_path = os.path.join(base_path, 'ASMD')
gaucher_path = os.path.join(base_path, 'Gaucher')
control_path = os.path.join(base_path, 'Gaucher-ASMD-Control')

print("ASMD Folder Contents:", os.listdir(asmd_path))
print("Gaucher Folder Contents:", os.listdir(gaucher_path))
print("Control Folder Contents:", os.listdir(control_path))

import os

# Listing files in each folder
print("ASMD Folder Contents:", os.listdir(asmd_path))
print("Gaucher Folder Contents:", os.listdir(gaucher_path))
print("Control Folder Contents:", os.listdir(control_path))

!pip install dask
!pip install "dask[dataframe]"

import dask.dataframe as dd
import os

# Defining paths
asmd_path = '/content/drive/My Drive/dataset/RareDiseaseAnalysis/ASMD'
gaucher_path = '/content/drive/My Drive/dataset/RareDiseaseAnalysis/Gaucher'
control_path = '/content/drive/My Drive/dataset/RareDiseaseAnalysis/Gaucher-ASMD-Control'

# Loading Parquet files using Dask
asmd_clinical = dd.read_parquet(os.path.join(asmd_path, 'Clinical_optimized.parquet'))
gaucher_clinical = dd.read_parquet(os.path.join(gaucher_path, 'Clinical_optimized.parquet'))
control_clinical = dd.read_parquet(os.path.join(control_path, 'Clinical_optimized.parquet'))

asmd_labs = dd.read_parquet(os.path.join(asmd_path, 'Labs_optimized.parquet'))
gaucher_labs = dd.read_parquet(os.path.join(gaucher_path, 'Labs_optimized.parquet'))
control_labs = dd.read_parquet(os.path.join(control_path, 'Labs_optimized.parquet'))

asmd_diagnosis = dd.read_parquet(os.path.join(asmd_path, 'Diagnosis_optimized.parquet'))
gaucher_diagnosis = dd.read_parquet(os.path.join(gaucher_path, 'Diagnosis_optimized.parquet'))
control_diagnosis = dd.read_parquet(os.path.join(control_path, 'Diagnosis_optimized.parquet'))

# Checking first few rows and columns of each dataset
print("ASMD Clinical Sample:")
print(asmd_clinical.head())

print("\nGaucher Clinical Sample:")
print(gaucher_clinical.head())

print("\nControl Clinical Sample:")
print(control_clinical.head())

print("ASMD Clinical Columns:", asmd_clinical.columns)
print("ASMD Labs Columns:", asmd_labs.columns)
print("ASMD Diagnosis Columns:", asmd_diagnosis.columns)

# Rule 1
def check_rule_1(person_id, diagnosis_df, labs_df):
# Checking for specific ICD codes in Diagnosis
    organomegaly_conditions = ['R19.0', 'R16.2', 'R16.0', 'R16.1']
    diagnosis_match = diagnosis_df[
        (diagnosis_df['PERSONID'] == person_id) &
        (diagnosis_df['ICDCODE'].isin(organomegaly_conditions))
    ].compute()  # Convert to pandas DataFrame

# Checking CBC parameters in Labs
    labs_match = labs_df[
        (labs_df['PERSONID'] == person_id) &
        (
            (labs_df['RESULTVALUE'] < 4.5) |  # WBC lower limit
            (labs_df['RESULTVALUE'] > 11) |  # WBC upper limit
            (labs_df['RESULTVALUE'] < 132) | # Hb lower limit
            (labs_df['RESULTVALUE'] > 173)   # Hb upper limit
        )
    ].compute()  # Convert to pandas DataFrame

    # Using pandas `.empty` now, as both DataFrames are converted
    return not diagnosis_match.empty and not labs_match.empty

# Applying Rule 1 to All Patients
import pandas as pd

# Getting unique PERSONID for ASMD dataset
asmd_person_ids = asmd_diagnosis['PERSONID'].compute().unique()
asmd_results = []

# Applying Rule 1 for ASMD
for person_id in asmd_person_ids:
    rule1 = check_rule_1(person_id, asmd_diagnosis, asmd_labs)
    asmd_results.append({'PERSONID': person_id, 'Rule 1': 'YES' if rule1 else 'NO'})

# Converting ASMD results to a DataFrame
asmd_results_df = pd.DataFrame(asmd_results)

# Repeating for Gaucher dataset
gaucher_person_ids = gaucher_diagnosis['PERSONID'].compute().unique()
gaucher_results = []

for person_id in gaucher_person_ids:
    rule1 = check_rule_1(person_id, gaucher_diagnosis, gaucher_labs)
    gaucher_results.append({'PERSONID': person_id, 'Rule 1': 'YES' if rule1 else 'NO'})

# Converting Gaucher results to a DataFrame
gaucher_results_df = pd.DataFrame(gaucher_results)

# Repeating for Control dataset
control_person_ids = control_diagnosis['PERSONID'].compute().unique()
control_results = []

for person_id in control_person_ids:
    rule1 = check_rule_1(person_id, control_diagnosis, control_labs)
    control_results.append({'PERSONID': person_id, 'Rule 1': 'YES' if rule1 else 'NO'})

# Converting Control results to a DataFrame
control_results_df = pd.DataFrame(control_results)

# Combining Results (ASMD + Control, Gaucher + Control)

# Adding labels to distinguish between ASMD, Gaucher, and Control
asmd_results_df['LABEL'] = 'YES'  # ASMD patients are diseased
gaucher_results_df['LABEL'] = 'YES'  # Gaucher patients are diseased
control_results_df['LABEL'] = 'NO'  # Control patients are not diseased

# Combining ASMD with Control
asmd_combined_results = pd.concat([asmd_results_df, control_results_df], ignore_index=True)

# Combining Gaucher with Control
gaucher_combined_results = pd.concat([gaucher_results_df, control_results_df], ignore_index=True)

# Adding prediction column for ASMD
asmd_combined_results['PREDICTION'] = asmd_combined_results['Rule 1'].apply(
    lambda x: 'YES' if x == 'YES' else 'NO'
)

# Adding prediction column for Gaucher
gaucher_combined_results['PREDICTION'] = gaucher_combined_results['Rule 1'].apply(
    lambda x: 'YES' if x == 'YES' else 'NO'
)

# Saving ASMD + Control results to CSV
asmd_combined_results.to_csv('asmd_combined_results.csv', index=False)

# Saving Gaucher + Control results to CSV
gaucher_combined_results.to_csv('gaucher_combined_results.csv', index=False)

from google.colab import files

# Downloading ASMD results
files.download('asmd_combined_results.csv')

# Downloading Gaucher results
files.download('gaucher_combined_results.csv')

from google.colab import drive
drive.mount('/content/drive')

# Moving the files to a specific folder in my Google Drive
!cp asmd_combined_results.csv '/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/'
!cp gaucher_combined_results.csv '/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/'

!ls '/content/drive/My Drive/dataset/RareDiseaseAnalysis/'

!mkdir '/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/'

!cp asmd_combined_results.csv '/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/'
!cp gaucher_combined_results.csv '/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/'

# Rule 2
def check_rule_2(person_id, diagnosis_df, rule1_result):

# Checking for Growth Retardation in Diagnosis
    growth_retardation_code = 'R62.50'
    diagnosis_match = diagnosis_df[
        (diagnosis_df['PERSONID'] == person_id) &
        (diagnosis_df['ICDCODE'] == growth_retardation_code)
    ]

# Rule 2 is triggered if Rule 1 is YES and growth retardation is present
    return rule1_result == 'YES' and not diagnosis_match.empty

# Applying Rule 2 for ASMD Ptients
asmd_results = []  # Initializing an empty list to store results

for person_id in asmd_person_ids:  # Iterate over unique PERSONIDs in ASMD
    rule1 = check_rule_1(person_id, asmd_diagnosis, asmd_labs)  # Apply Rule 1
    rule2 = check_rule_2(person_id, asmd_diagnosis, rule1)  # Apply Rule 2

    asmd_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO'
    })

# Converting results to a DataFrame
asmd_results_df = pd.DataFrame(asmd_results)

# Applying Rule 2 for Gaucher Patients
gaucher_results = []
for person_id in gaucher_person_ids:
    rule1 = check_rule_1(person_id, gaucher_diagnosis, gaucher_labs)
    rule2 = check_rule_2(person_id, gaucher_diagnosis, rule1)

    gaucher_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO'
    })

gaucher_results_df = pd.DataFrame(gaucher_results)

# Applying Rule 2 for Control Patients
control_results = []
for person_id in control_person_ids:
    rule1 = check_rule_1(person_id, control_diagnosis, control_labs)
    rule2 = check_rule_2(person_id, control_diagnosis, rule1)

    control_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO'
    })

control_results_df = pd.DataFrame(control_results)

# Displaying sample results for ASMD
print(asmd_results_df.head())

# Displaying sample results for Gaucher
print(gaucher_results_df.head())

# Displaying sample results for Control
print(control_results_df.head())

# Saving ASMD Rule 2 results
asmd_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/asmd_rule2_results.csv', index=False)

# Saving Gaucher Rule 2 results
gaucher_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/gaucher_rule2_results.csv', index=False)

# Saving Control Rule 2 results
control_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/control_rule2_results.csv', index=False)

# Rule 3
def check_rule_3(person_id, diagnosis_df, clinical_df, rule1_result, rule2_result):
# Checking for Growth Retardation OR Failure to Thrive OR Low Weight/Height Percentile
    growth_conditions = ['R62.50', 'R62.7']  # Growth retardation and failure to thrive
    diagnosis_match = diagnosis_df[
        (diagnosis_df['PERSONID'] == person_id) &
        (diagnosis_df['ICDCODE'].isin(growth_conditions))
    ]

# Checking for low weight or height percentiles
    clinical_match = clinical_df[
        (clinical_df['PERSONID'] == person_id) &
        (clinical_df['EVENTNAME'].str.contains('WEIGHT|HEIGHT', na=False)) &
        (clinical_df['EVENTRESULT'].astype(float) < 3)  # Below 3rd percentile
    ]

# Rule 3 is triggered if Rule 1 and Rule 2 are YES and conditions are met
    return (
        rule1_result == 'YES' and
        rule2_result == 'YES' and
        (not diagnosis_match.empty or not clinical_match.empty)
    )

# Applying Rule 3 for ASMD Patients
for person_id in asmd_person_ids:
    rule1 = check_rule_1(person_id, asmd_diagnosis, asmd_labs)
    rule2 = check_rule_2(person_id, asmd_diagnosis, rule1)
    rule3 = check_rule_3(person_id, asmd_diagnosis, asmd_clinical, rule1, rule2)

    asmd_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO'
    })

# Converting to DataFrame
asmd_results_df = pd.DataFrame(asmd_results)

# Applying Rule 3 for Gaucher Patients
gaucher_results = []
for person_id in gaucher_person_ids:
    rule1 = check_rule_1(person_id, gaucher_diagnosis, gaucher_labs)
    rule2 = check_rule_2(person_id, gaucher_diagnosis, rule1)
    rule3 = check_rule_3(person_id, gaucher_diagnosis, gaucher_clinical, rule1, rule2)

    gaucher_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO'
    })

# Converting to DataFrame
gaucher_results_df = pd.DataFrame(gaucher_results)

# Applying Rule 3 for Control
control_results = []
for person_id in control_person_ids:
    rule1 = check_rule_1(person_id, control_diagnosis, control_labs)
    rule2 = check_rule_2(person_id, control_diagnosis, rule1)
    rule3 = check_rule_3(person_id, control_diagnosis, control_clinical, rule1, rule2)

    control_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO'
    })

# Converting to DataFrame
control_results_df = pd.DataFrame(control_results)

# Verifying ASMD results
print(asmd_results_df.head())

# Verifying Gaucher results
print(gaucher_results_df.head())

# Verifying Control results
print(control_results_df.head())

# Saving ASMD results after Rule 3
asmd_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/asmd_rule3_results.csv', index=False)

# Saving Gaucher results after Rule 3
gaucher_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/gaucher_rule3_results.csv', index=False)

# Saving Control results after Rule 3
control_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/control_rule3_results.csv', index=False)

# Rule 4
def check_rule_4(person_id, diagnosis_df, rule1_result):
# Checking for Interstitial Lung Disease in Diagnosis
    lung_disease_code = 'J84.9'
    diagnosis_match = diagnosis_df[
        (diagnosis_df['PERSONID'] == person_id) &
        (diagnosis_df['ICDCODE'] == lung_disease_code)
    ]

# Rule 4 is triggered if Rule 1 is YES and lung disease is present
    return rule1_result == 'YES' and not diagnosis_match.empty

# Applying Rule 4 for ASMD
asmd_results = []
for person_id in asmd_person_ids:
    rule1 = check_rule_1(person_id, asmd_diagnosis, asmd_labs)
    rule2 = check_rule_2(person_id, asmd_diagnosis, rule1)
    rule3 = check_rule_3(person_id, asmd_diagnosis, asmd_clinical, rule1, rule2)
    rule4 = check_rule_4(person_id, asmd_diagnosis, rule1)

    asmd_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO',
        'Rule 4': 'YES' if rule4 else 'NO'
    })

asmd_results_df = pd.DataFrame(asmd_results)

# Applying Rule 4 for Gaucher
gaucher_results = []
for person_id in gaucher_person_ids:
    rule1 = check_rule_1(person_id, gaucher_diagnosis, gaucher_labs)
    rule2 = check_rule_2(person_id, gaucher_diagnosis, rule1)
    rule3 = check_rule_3(person_id, gaucher_diagnosis, gaucher_clinical, rule1, rule2)
    rule4 = check_rule_4(person_id, gaucher_diagnosis, rule1)

    gaucher_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO',
        'Rule 4': 'YES' if rule4 else 'NO'
    })

gaucher_results_df = pd.DataFrame(gaucher_results)

# Applying Rule 4 for Control
control_results = []
for person_id in control_person_ids:
    rule1 = check_rule_1(person_id, control_diagnosis, control_labs)
    rule2 = check_rule_2(person_id, control_diagnosis, rule1)
    rule3 = check_rule_3(person_id, control_diagnosis, control_clinical, rule1, rule2)
    rule4 = check_rule_4(person_id, control_diagnosis, rule1)

    control_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO',
        'Rule 4': 'YES' if rule4 else 'NO'
    })

control_results_df = pd.DataFrame(control_results)

# Verifying ASMD results
print(asmd_results_df.head())

# Verifying Gaucher results
print(gaucher_results_df.head())

# Verifying Control results
print(control_results_df.head())

# Saving ASMD results after Rule 4
asmd_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/asmd_rule4_results.csv', index=False)

# Saving Gaucher results after Rule 4
gaucher_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/gaucher_rule4_results.csv', index=False)

# Saving Control results after Rule 4
control_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/control_rule4_results.csv', index=False)

# Rule 5
def check_rule_5(person_id, diagnosis_df, rule1_result):
# Checking for Hypotonia or Developmental Delay
    delay_conditions = ['P94.2', 'R62.50', 'R62.59']
    diagnosis_match = diagnosis_df[
        (diagnosis_df['PERSONID'] == person_id) &
        (diagnosis_df['ICDCODE'].isin(delay_conditions))
    ]

# Rule 5 is triggered if Rule 1 is YES and any delay condition is present
    return rule1_result == 'YES' and not diagnosis_match.empty

# Applying Rule 5 for ASMD Patients
asmd_results = []
for person_id in asmd_person_ids:
    rule1 = check_rule_1(person_id, asmd_diagnosis, asmd_labs)
    rule2 = check_rule_2(person_id, asmd_diagnosis, rule1)
    rule3 = check_rule_3(person_id, asmd_diagnosis, asmd_clinical, rule1, rule2)
    rule4 = check_rule_4(person_id, asmd_diagnosis, rule1)
    rule5 = check_rule_5(person_id, asmd_diagnosis, rule1)

    asmd_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO',
        'Rule 4': 'YES' if rule4 else 'NO',
        'Rule 5': 'YES' if rule5 else 'NO'
    })

asmd_results_df = pd.DataFrame(asmd_results)

# Applying Rule 5 for Gaucher
gaucher_results = []
for person_id in gaucher_person_ids:
    rule1 = check_rule_1(person_id, gaucher_diagnosis, gaucher_labs)
    rule2 = check_rule_2(person_id, gaucher_diagnosis, rule1)
    rule3 = check_rule_3(person_id, gaucher_diagnosis, gaucher_clinical, rule1, rule2)
    rule4 = check_rule_4(person_id, gaucher_diagnosis, rule1)
    rule5 = check_rule_5(person_id, gaucher_diagnosis, rule1)

    gaucher_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO',
        'Rule 4': 'YES' if rule4 else 'NO',
        'Rule 5': 'YES' if rule5 else 'NO'
    })

gaucher_results_df = pd.DataFrame(gaucher_results)

# Applying Rule 5 for Control
control_results = []
for person_id in control_person_ids:
    rule1 = check_rule_1(person_id, control_diagnosis, control_labs)
    rule2 = check_rule_2(person_id, control_diagnosis, rule1)
    rule3 = check_rule_3(person_id, control_diagnosis, control_clinical, rule1, rule2)
    rule4 = check_rule_4(person_id, control_diagnosis, rule1)
    rule5 = check_rule_5(person_id, control_diagnosis, rule1)

    control_results.append({
        'PERSONID': person_id,
        'Rule 1': 'YES' if rule1 else 'NO',
        'Rule 2': 'YES' if rule2 else 'NO',
        'Rule 3': 'YES' if rule3 else 'NO',
        'Rule 4': 'YES' if rule4 else 'NO',
        'Rule 5': 'YES' if rule5 else 'NO'
    })

control_results_df = pd.DataFrame(control_results)

# Verifying ASMD results
print(asmd_results_df.head())

# Verifying Gaucher results
print(gaucher_results_df.head())

# Verifying Control results
print(control_results_df.head())

# Saving ASMD results after Rule 5
asmd_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/asmd_final_results.csv', index=False)

# Saving Gaucher results after Rule 5
gaucher_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/gaucher_final_results.csv', index=False)

# Saving Control results after Rule 5
control_results_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/control_final_results.csv', index=False)

# Final Steps

# Adding LABEL column for ASMD
asmd_results_df['LABEL'] = 'YES'

# Adding LABEL column for Gaucher
gaucher_results_df['LABEL'] = 'YES'

# Adding LABEL column for Control
control_results_df['LABEL'] = 'NO'

# Adding PREDICTION column for ASMD
# (The PREDICTION column should be "YES" if any rule is triggered, otherwise "NO")

asmd_results_df['PREDICTION'] = asmd_results_df[['Rule 1', 'Rule 2', 'Rule 3', 'Rule 4', 'Rule 5']].apply(
    lambda row: 'YES' if 'YES' in row.values else 'NO', axis=1
)

# Adding PREDICTION column for Gaucher
gaucher_results_df['PREDICTION'] = gaucher_results_df[['Rule 1', 'Rule 2', 'Rule 3', 'Rule 4', 'Rule 5']].apply(
    lambda row: 'YES' if 'YES' in row.values else 'NO', axis=1
)

# Adding PREDICTION column for Control
control_results_df['PREDICTION'] = control_results_df[['Rule 1', 'Rule 2', 'Rule 3', 'Rule 4', 'Rule 5']].apply(
    lambda row: 'YES' if 'YES' in row.values else 'NO', axis=1
)

# Combining Results

# Combining ASMD + Control
asmd_combined_df = pd.concat([asmd_results_df, control_results_df])

# Combining Gaucher + Control
gaucher_combined_df = pd.concat([gaucher_results_df, control_results_df])

# Saving Final Combined Results

# Saving ASMD + Control results
asmd_combined_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/asmd_combined_results.csv', index=False)

# Saving Gaucher + Control results
gaucher_combined_df.to_csv('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/gaucher_combined_results.csv', index=False)

# Verification
# Displaying ASMD + Control combined results
print(asmd_combined_df.head())

# Displaying Gaucher + Control combined results
print(gaucher_combined_df.head())

# Downloading the final combined CSV files
from google.colab import files

# Downloading ASMD + Control results
files.download('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/asmd_combined_results.csv')

# Downloading Gaucher + Control results
files.download('/content/drive/My Drive/dataset/RareDiseaseAnalysis/Results/gaucher_combined_results.csv')